# Generated by Django 5.0.4 on 2024-04-15 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], default='Low', error_messages={'invalid_choice': 'Invalid importance value. Please choose from "Low", "Medium", or "High".'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(error_messages={'invalid': 'Please enter a valid creator.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, error_messages={'max_length': 'Please enter a valid description. The description should be less than 2000 characters long.'}),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(error_messages={'invalid': 'Please enter a valid due date. The date should be in the format YYYY-MM-DD HH:MM:SS.'}),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'blank': 'This field is required. Please provide a value.', 'max_length': 'Please enter a valid title. The title should be between 1 and 200 characters long.'}, max_length=200),
        ),
    ]
